import { type MigrateDownArgs, type MigrateUpArgs, sql } from "@payloadcms/db-postgres";

// The "Volt képviselők" list of the old website (ehk-regi.kir-dev.hu/szervezet/h).
// These representatives already exist in the CMS; this only marks them as former.
const formerRepresentativeNames = [
  "Lévai Imre",
  "Rajtik Dóra Vivien",
  "Varga Kitti",
  "Langár Ákos István",
  "Miokovics Patrik",
  "Papp Bercel",
  "Kovács Laura",
  "Horváth Adrián Márk",
  "Veliczky Zsófia",
  "Márton Ágnes",
  "Dreiszig Dániel",
  "Nyilas Zoltán",
  "Rajczi Barnabás",
  "Hegyes József",
  "Kovács Brúnó Aurél",
  "Smuk András",
  "Csaplár Miklós Máté",
  "Lengyel Zsolt",
  "Baranyai Dóra Eszter",
  "Radácsi Kristóf",
  "Zöllner Lili",
  "Vámosi Anna",
  "Antal Jázmin",
  "Kovács Kíra Diána",
  "Vigyikán Vince",
  "Kékesi Márton Gábor",
  "Szatzger Martin",
  "Pusztay Botond",
  "Nagy Levente",
  "Sajtos Judit",
  "Lukács Bálint",
  "Koronczai Fanni",
  "Bódig Péter",
  "Nagy Ynna Ilona",
  "Gombás Bálint",
  "Kiss Mirjam Cecília",
  "Felföldi Árpád",
  "Lénárt Adél Lujza",
  "Koltai Kristóf",
  "Béres Máté",
  "Papp Bendegúz",
  "Varga Viktor",
  "Bátori Boglárka",
  "Lipták Bence",
  "Tani Zoltán",
  "Szili Ákos",
  "Szabó Dániel",
  "Takács Dalma",
  "Merkei Dóra",
  "Szabó Kármen Emőke",
  "Németh Csongor Gergely",
  "Csábi Eszter Zsófia",
  "Zoller Zita",
  "Magyar Boglárka",
  "Szalay Luca",
  "Walton Mihály",
  "Józsa Alex",
  "Dovicsin Péter",
  "Varga Balázs",
  "Kocsi József",
  "Pecze Levente",
  "Dáni Eszter",
  "Vuics Márton",
  "Szenka József",
  "Grizák Máté",
  "Puskely Gergő",
  "Varga Ferenc",
  "Boros Gergő",
  "Haász Alida",
  "Kovács Klementina",
  "Pollák Zsombor",
  "Lestyan Bence",
  "Török Lili",
  "Egyed Gábor",
  "Barabás Zoltán",
  "Pekár Zoltán",
  "Mráz Marcell",
  "Horváth Bálint",
  "Módos Dávid",
  "Suhajda Richárd",
  "R. Nagy Tibor Endre",
  "Leicht Ferenc",
  "Kántor Tamás",
  "Lőrincz László",
  "Gődér Nikoletta",
  "Molnár Zsanett",
  "Beluzsár Ádám",
  "Katona Rebeka",
  "Oroszki Norbert",
  "Gál Bernadett",
  "Nagy Benjámin",
  "Schaf Alexa Lili",
  "Krisztián Dávid",
  "Kovalovszki Máté",
  "Vidák Miklós",
  "Kiss Viktor",
  "Gődér Vivien",
  "Csősz Gábor",
  "Mráz Márk",
  "Gácsig Gergő",
  "Nagy Edit",
  "Lövei Dorottya Rebeka",
  "Görbe Richárd",
  "Magyar Zoltán",
  "Markovics Petra",
  "Németh Péter",
  "Nagy Renáta",
  "Traxler Balázs",
  "Daku Dávid",
  "Kun Levente Alex",
  "Lábas István",
  "Rácz Tamás",
  "Ónodi Áron",
  "Tompos Balázs",
  "Németh Ákos Zoltán",
  "Farkas László",
  "Szücs Krisztián Bulcsu",
  "Molnár László",
  "Somogyi József",
  "Varga Ágoston",
  "Rynkiewicz Ádám",
  "Jóvér Vivien",
  "Jámbori Attila",
];

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const name of formerRepresentativeNames) {
    await db.execute(sql`
      UPDATE "representatives" SET "former" = true WHERE "name" = ${name};
    `);
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  for (const name of formerRepresentativeNames) {
    await db.execute(sql`
      UPDATE "representatives" SET "former" = false WHERE "name" = ${name};
    `);
  }
}
