/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clubs: Club;
    media: Media;
    representatives: Representative;
    reminders: Reminder;
    news: News;
    'hero-images': HeroImage;
    'muszak-paper': MuszakPaper;
    decisions: Decision;
    events: Event;
    'ehk-events': EhkEvent;
    'ehk-scholarships': EhkScholarship;
    permissions: Permission;
    regulations: Regulation;
    help: Help;
    'payout-periods': PayoutPeriod;
    'university-pages': UniversityPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    representatives: RepresentativesSelect<false> | RepresentativesSelect<true>;
    reminders: RemindersSelect<false> | RemindersSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'hero-images': HeroImagesSelect<false> | HeroImagesSelect<true>;
    'muszak-paper': MuszakPaperSelect<false> | MuszakPaperSelect<true>;
    decisions: DecisionsSelect<false> | DecisionsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'ehk-events': EhkEventsSelect<false> | EhkEventsSelect<true>;
    'ehk-scholarships': EhkScholarshipsSelect<false> | EhkScholarshipsSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    regulations: RegulationsSelect<false> | RegulationsSelect<true>;
    help: HelpSelect<false> | HelpSelect<true>;
    'payout-periods': PayoutPeriodsSelect<false> | PayoutPeriodsSelect<true>;
    'university-pages': UniversityPagesSelect<false> | UniversityPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'academic-scholarship-faq': AcademicScholarshipFaq;
    'social-scholarships-faq': SocialScholarshipsFaq;
  };
  globalsSelect: {
    'academic-scholarship-faq': AcademicScholarshipFaqSelect<false> | AcademicScholarshipFaqSelect<true>;
    'social-scholarships-faq': SocialScholarshipsFaqSelect<false> | SocialScholarshipsFaqSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Felhasználók, akik be tudnak jelentkezni az admin felületre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: number;
  /**
   * A klub neve
   */
  title: string;
  description: {
    text_hu: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    text_en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Cím vagy helyszín, pl.: Kármán Tódor Kollégium
   */
  location?: string | null;
  openingHours?: {
    text_hu?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    text_en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * A klub kártyáján megjelenő nagy borítókép
   */
  image?: (number | null) | Media;
  /**
   * Képek a galéria karuszelhez
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenítési sorrend (pl. 1 az első)
   */
  order?: number | null;
  /**
   * Opcionális link a klub weboldalához vagy közösségi oldalához. Csak érvényes HTTP vagy HTTPS URL megengedett.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Képviselők adatainak kezelése. Beszámolók feltöltése.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representatives".
 */
export interface Representative {
  id: number;
  name: string;
  position?:
    | {
        position_hu: string;
        position_en: string;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  picture?: (number | null) | Media;
  introduction: {
    text_hu: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    text_en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  faculty?: ('ÉMK' | 'GPK' | 'ÉPK' | 'VBK' | 'VIK' | 'GTK' | 'TTK' | 'KJK') | null;
  order?: number | null;
  files?:
    | {
        file: number | Media;
        title_hu: string;
        title_en?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Emlékeztetők kezelése.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders".
 */
export interface Reminder {
  id: number;
  date: string;
  displayText: string;
  file: number | Media;
  type: 'EHK' | 'EHDK';
  updatedAt: string;
  createdAt: string;
}
/**
 * Hírek gyűjteménye
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  titleEng: string;
  shortDescription: {
    text_hu: string;
    text_en: string;
  };
  description: {
    text_hu: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    text_en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  date: string;
  tags: (
    | 'EHK'
    | 'Oktatás'
    | 'Juttatás'
    | 'Kollégium'
    | 'Pályázat'
    | 'Sport'
    | 'Külügy'
    | 'Rendezvények'
    | 'Közélet'
    | 'Felhívás'
    | 'Beszámoló'
    | 'Tájékoztatás'
    | 'Kiemelt hír'
    | 'International'
    | 'TDK ösztöndíj'
    | 'Sportpálya pályázat'
    | 'Sportpálya igénylés'
  )[];
  files?:
    | {
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcionális. A híret kísérő kapcsolattartó képviselő (név, pozíció és alapértelmezett e-mail cím az Elérhetőségek dobozhoz).
   */
  representative?: (number | null) | Representative;
  /**
   * Opcionális. Közvetlen kapcsolattartó e-mail cím, a képviselő mellett vagy helyett megjeleníthető.
   */
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hírek gyűjteménye
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images".
 */
export interface HeroImage {
  id: number;
  title: string;
  picture: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * MŰszak hírek, események és információk gyűjteménye.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "muszak-paper".
 */
export interface MuszakPaper {
  id: number;
  title: string;
  titleEng: string;
  date: string;
  picture: number | Media;
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Határozatok kezelése.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions".
 */
export interface Decision {
  id: number;
  text_hu: string;
  text_en: string;
  displayText: string;
  file: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Események gyűjteménye - egy napos és többszörös napos eseményekhez
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title_hu: string;
  title_en: string;
  shortDescription: {
    description_hu: string;
    description_en: string;
  };
  date: {
    startDate: string;
    /**
     * Ha egy napos esemény, akkor ugyanaz legyen mint a kezdő dátum
     */
    endDate: string;
  };
  location?: {
    location_hu?: string | null;
    location_en?: string | null;
  };
  image?: (number | null) | Media;
  detailedDescription?: {
    description_hu?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    description_en?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  facebookUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ehk-events".
 */
export interface EhkEvent {
  id: number;
  title: string;
  description: {
    text_hu: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    text_en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  order?: number | null;
  /**
   * Eseményhez tartozó weboldal, Facebook, vagy más hivatkozások.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Az EHK ösztöndíjak oldal lenyíló szekcióinak szerkeszthető tartalma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ehk-scholarships".
 */
export interface EhkScholarship {
  id: number;
  title_hu: string;
  title_en: string;
  content_hu: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Megjelenítési sorrend. A kisebb szám jelenik meg előbb.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Engedélyek kezelése.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  name_hu: string;
  name_en: string;
  text_hu: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  text_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * A "BENYÚJTÁS MENETE" szekció tartalma.
   */
  submissionProcess_hu?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A "BENYÚJTÁS MENETE" szekció tartalma angolul.
   */
  submissionProcess_en?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  displayText_hu?: string | null;
  displayText_en?: string | null;
  file?: (number | null) | Media;
  /**
   * Külső webes űrlaphoz tartozó URL (pl. "Rendezvénybejelentő űrlap"). Ha meg van adva, a kártya ezt nyitja meg fájl helyett.
   */
  externalLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Szabályzatok kezelése.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations".
 */
export interface Regulation {
  id: number;
  name_hu: string;
  name_en: string;
  text_hu: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  text_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  displayText_hu?: string | null;
  displayText_en?: string | null;
  file?: (number | null) | Media;
  file_eng?: (number | null) | Media;
  type: 'academic' | 'benefits' | 'dormitory';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help".
 */
export interface Help {
  id: number;
  title_hu: string;
  title_en: string;
  description_hu: string;
  description_en: string;
  files?:
    | {
        displayName_hu: string;
        file_hu: number | Media;
        displayName_en?: string | null;
        file_en?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-periods".
 */
export interface PayoutPeriod {
  id: number;
  title: string;
  /**
   * Ha bepipálod, ez lesz az aktuálisan megjelenő időszak az oldalon. (A többi automatikusan inaktív lesz.)
   */
  isActive?: boolean | null;
  autumnSemester?: {
    payouts?:
      | {
          month_hu: string;
          month_en: string;
          date: string;
          id?: string | null;
        }[]
      | null;
  };
  springSemester?: {
    payouts?:
      | {
          month_hu: string;
          month_en: string;
          date: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Egyetemi oldalak linkjeinek kezelése a láblécben.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-pages".
 */
export interface UniversityPage {
  id: number;
  title_hu: string;
  title_en: string;
  url: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clubs';
        value: number | Club;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'representatives';
        value: number | Representative;
      } | null)
    | ({
        relationTo: 'reminders';
        value: number | Reminder;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'hero-images';
        value: number | HeroImage;
      } | null)
    | ({
        relationTo: 'muszak-paper';
        value: number | MuszakPaper;
      } | null)
    | ({
        relationTo: 'decisions';
        value: number | Decision;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'ehk-events';
        value: number | EhkEvent;
      } | null)
    | ({
        relationTo: 'ehk-scholarships';
        value: number | EhkScholarship;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'regulations';
        value: number | Regulation;
      } | null)
    | ({
        relationTo: 'help';
        value: number | Help;
      } | null)
    | ({
        relationTo: 'payout-periods';
        value: number | PayoutPeriod;
      } | null)
    | ({
        relationTo: 'university-pages';
        value: number | UniversityPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  title?: T;
  description?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  location?: T;
  openingHours?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  order?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "representatives_select".
 */
export interface RepresentativesSelect<T extends boolean = true> {
  name?: T;
  position?:
    | T
    | {
        position_hu?: T;
        position_en?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  picture?: T;
  introduction?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  faculty?: T;
  order?: T;
  files?:
    | T
    | {
        file?: T;
        title_hu?: T;
        title_en?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders_select".
 */
export interface RemindersSelect<T extends boolean = true> {
  date?: T;
  displayText?: T;
  file?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  titleEng?: T;
  shortDescription?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  description?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  date?: T;
  tags?: T;
  files?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  representative?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-images_select".
 */
export interface HeroImagesSelect<T extends boolean = true> {
  title?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "muszak-paper_select".
 */
export interface MuszakPaperSelect<T extends boolean = true> {
  title?: T;
  titleEng?: T;
  date?: T;
  picture?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions_select".
 */
export interface DecisionsSelect<T extends boolean = true> {
  text_hu?: T;
  text_en?: T;
  displayText?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title_hu?: T;
  title_en?: T;
  shortDescription?:
    | T
    | {
        description_hu?: T;
        description_en?: T;
      };
  date?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  location?:
    | T
    | {
        location_hu?: T;
        location_en?: T;
      };
  image?: T;
  detailedDescription?:
    | T
    | {
        description_hu?: T;
        description_en?: T;
      };
  facebookUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ehk-events_select".
 */
export interface EhkEventsSelect<T extends boolean = true> {
  title?: T;
  description?:
    | T
    | {
        text_hu?: T;
        text_en?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  order?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ehk-scholarships_select".
 */
export interface EhkScholarshipsSelect<T extends boolean = true> {
  title_hu?: T;
  title_en?: T;
  content_hu?: T;
  content_en?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name_hu?: T;
  name_en?: T;
  text_hu?: T;
  text_en?: T;
  submissionProcess_hu?: T;
  submissionProcess_en?: T;
  displayText_hu?: T;
  displayText_en?: T;
  file?: T;
  externalLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations_select".
 */
export interface RegulationsSelect<T extends boolean = true> {
  name_hu?: T;
  name_en?: T;
  text_hu?: T;
  text_en?: T;
  displayText_hu?: T;
  displayText_en?: T;
  file?: T;
  file_eng?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help_select".
 */
export interface HelpSelect<T extends boolean = true> {
  title_hu?: T;
  title_en?: T;
  description_hu?: T;
  description_en?: T;
  files?:
    | T
    | {
        displayName_hu?: T;
        file_hu?: T;
        displayName_en?: T;
        file_en?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-periods_select".
 */
export interface PayoutPeriodsSelect<T extends boolean = true> {
  title?: T;
  isActive?: T;
  autumnSemester?:
    | T
    | {
        payouts?:
          | T
          | {
              month_hu?: T;
              month_en?: T;
              date?: T;
              id?: T;
            };
      };
  springSemester?:
    | T
    | {
        payouts?:
          | T
          | {
              month_hu?: T;
              month_en?: T;
              date?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "university-pages_select".
 */
export interface UniversityPagesSelect<T extends boolean = true> {
  title_hu?: T;
  title_en?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * A Tanulmányi ösztöndíj oldal lenyíló (akkordeon) szekcióinak tartalma. A szekciók sorrendje húzással átrendezhető.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-scholarship-faq".
 */
export interface AcademicScholarshipFaq {
  id: number;
  accordionItems?:
    | {
        header_hu: string;
        header_en: string;
        content_hu: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        content_en: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A Szociális ösztöndíj oldal kártyáinak és fontos linkjeinek szerkeszthető tartalma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-scholarships-faq".
 */
export interface SocialScholarshipsFaq {
  id: number;
  scholarshipTypes?:
    | {
        title_hu: string;
        title_en: string;
        targetAudience_hu: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        targetAudience_en: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        description_hu: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        description_en: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        actionLink: string;
        id?: string | null;
      }[]
    | null;
  sidebarLinks?:
    | {
        title_hu: string;
        title_en: string;
        description_hu: string;
        description_en: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-scholarship-faq_select".
 */
export interface AcademicScholarshipFaqSelect<T extends boolean = true> {
  accordionItems?:
    | T
    | {
        header_hu?: T;
        header_en?: T;
        content_hu?: T;
        content_en?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-scholarships-faq_select".
 */
export interface SocialScholarshipsFaqSelect<T extends boolean = true> {
  scholarshipTypes?:
    | T
    | {
        title_hu?: T;
        title_en?: T;
        targetAudience_hu?: T;
        targetAudience_en?: T;
        description_hu?: T;
        description_en?: T;
        actionLink?: T;
        id?: T;
      };
  sidebarLinks?:
    | T
    | {
        title_hu?: T;
        title_en?: T;
        description_hu?: T;
        description_en?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}